use PLANILLAS_DANIELH


/* 
	---Objetivo:
	OBTENER LAS INCAPACIDADES DEL MES ANTERIOR A LA FECHA DEL CALCULO

	---COMENTARIOS:
	EN LA APLICACION SE DEBE VERIFICAR SI 
	1. LA FECHA DE INICIO Y FIN SON PARTE DEL MES
	2. SI LA FECHA DE INICIO ES PARTE DEL MES SE DEBE VERIFICAR CONTRA EL ÚLTIMO DÍA DEL MES 
	3. SI LA FECHA DE FIN ES DEL MES PERO LA DE INICIO DE OTRO SE DEBEN CALCULAR LA DIFERENCIA ENTRE EL PRIMER DÍA DEL MES Y LA FECHA FIN
*/
SELECT EMPLEADO_ID, NOMBRE, FECHA_INICIO, FECHA_FIN, DATEDIFF(DAY, FECHA_INICIO, FECHA_FIN) AS DIAS_INCAPACIDAD
FROM EMPLEADOS E 
LEFT JOIN INCAPACIDADES I
ON E.ID = I.EMPLEADO_ID
WHERE MONTH(FECHA_INICIO) = (MONTH(GETDATE())-1) OR 
MONTH(FECHA_FIN) = (MONTH(GETDATE())-1)


select MONTH(GETDATE())-1

SELECT EMPLEADO_ID, FECHA_INICIO, FECHA_FIN FROM INCAPACIDADES WHERE (MONTH(FECHA_INICIO) = (MONTH(GETDATE())-1) OR (MONTH(GETDATE())-1) = MONTH(FECHA_FIN)) AND (YEAR(FECHA_INICIO) = (YEAR(GETDATE())) OR (YEAR(GETDATE())) = YEAR(FECHA_FIN))

SELECT * 
FROM EMPLEADOS E
INNER JOIN NOMBRAMIENTOS N
ON E.ID = N.EMPLEADO_ID
WHERE E.BORRADO = 0 AND N.ESTADO = 'ACT'

select * from DETALLES_PLANILLA

delete from DETALLES_PLANILLA
dbcc checkident('detalles_planilla', reseed, 0)
delete from planillas
dbcc checkident('planillas', reseed, 0)


select EMPLEADO_ID, SALARIO_BASE, SALARIO_GLOBAL, ES_SALARIOGLOBAL, P.CATEGORIA, FECHAI_NOMBRAMIENTO, FECHAF_NOMBRAMIENTO 
from NOMBRAMIENTOS N
INNER JOIN PUESTOS P
ON N.PUESTO_ID = P.ID
WHERE N.ESTADO = 'ACT' 


select * from DETALLES_PLANILLA dp
inner join EMPLEADOS e
on e.ID = dp.EMPLEADO_ID


select * from PERMISOS



select nombre, e.id, FECHAI_NOMBRAMIENTO, FECHAF_NOMBRAMIENTO, I.FECHA_INICIO, I.FECHA_FIN 
from EMPLEADOS e
left join NOMBRAMIENTOS n
on e.ID = n.EMPLEADO_ID
LEFT JOIN INCAPACIDADES I
ON E.ID = I.EMPLEADO_ID

SELECT * FROM EMPLEADOS E
INNER JOIN NOMBRAMIENTOS N
ON E.ID = N.EMPLEADO_ID
WHERE E.ID = '301410001'

INSERT INTO PERMISOS values 
('Estudio en el extranjero', 0, '20250124', '20250712', 'APR', '301410001')

DBCC CHECKIDENT('PERMISOS', RESEED, 0)

SELECT * FROM PUESTOS

SELECT E.ID, E.NOMBRE, E.APELLIDO_1, E.APELLIDO_2, E.CORREO, E.TELEFONO, E.FECHA_NACIMIENTO FROM EMPLEADOS E INNER JOIN NOMBRAMIENTOS N ON E.ID = N.EMPLEADO_ID WHERE E.BORRADO = 0 AND N.ESTADO = 'ACT'

SELECT 
DP.ID AS DETALLES_ID,
AJS.ID AS AJUSTES_ID,
DP.EMPLEADO_ID,
AJS.DESCRIPRCION,
AJS.ES_DEDUCCION,
P.CATEGORIA	AS CATEGORIA_PUESTO
FROM PUESTOS P
INNER JOIN NOMBRAMIENTOS N ON P.ID = N.PUESTO_ID
INNER JOIN DETALLES_PLANILLA DP ON N.EMPLEADO_ID = DP.EMPLEADO_ID AND DP.EMPLEADO_ID = '301410001'
INNER JOIN AJUSTES_SALARIALES AJS ON P.CATEGORIA >= AJS.CATEGORIA
WHERE N.ESTADO = 'ACT' AND AJS.ESTADO = 'ACT' AND (MONTH(FECHA_PAGO1) = MONTH(GETDATE())) 

	select EMPLEADO_ID
	from DETALLES_PLANILLA
	ORDER BY EMPLEADO_ID
	   