use PLANILLAS_DANIELH


/* 
	---Objetivo:
	OBTENER LAS INCAPACIDADES DEL MES ANTERIOR A LA FECHA DEL CALCULO

	---COMENTARIOS:
	EN LA APLICACION SE DEBE VERIFICAR SI 
	1. LA FECHA DE INICIO Y FIN SON PARTE DEL MES
	2. SI LA FECHA DE INICIO ES PARTE DEL MES SE DEBE VERIFICAR CONTRA EL ÚLTIMO DÍA DEL MES 
	3. SI LA FECHA DE FIN ES DEL MES PERO LA DE INICIO DE OTRO SE DEBEN CALCULAR LA DIFERENCIA ENTRE EL PRIMER DÍA DEL MES Y LA FECHA FIN
*/
SELECT EMPLEADO_ID, NOMBRE, FECHA_INICIO, FECHA_FIN, DATEDIFF(DAY, FECHA_INICIO, FECHA_FIN) AS DIAS_INCAPACIDAD
FROM EMPLEADOS E 
LEFT JOIN INCAPACIDADES I
ON E.ID = I.EMPLEADO_ID
WHERE MONTH(FECHA_INICIO) = (MONTH(GETDATE())-1) OR 
MONTH(FECHA_FIN) = (MONTH(GETDATE())-1)




SELECT *
FROM EMPLEADOS