USE MASTER
GO
USE PLANILLAS_DANIELH
GO
/*
	TRIGGER QUE VALIDA QUE SE ESTÉ INSERTANDO UN EMPLEADO CON TÍTULO UNIVERSITARIO
	EN UN PUESTO DE CATEGORIA 2
*/
CREATE TRIGGER TR_CATEGORIA2_TITULO_UNIVERSITARIO
ON NOMBRAMIENTOS AFTER INSERT 
AS
	BEGIN 	
		IF EXISTS(SELECT 1
			FROM inserted I
			JOIN PUESTOS P ON I.PUESTO_ID = P.ID 
			LEFT JOIN (
				SELECT EMPLEADO_ID
				FROM CARRERA_PROFESIONAL CP
				INNER JOIN GRADOS_ACADEMICOS GA
				ON GA.ID = CP.GRADO_ID
				WHERE GA.CATEGORIA = 2
			) AS EmpleadoUni on I.EMPLEADO_ID = EmpleadoUni.EMPLEADO_ID
			WHERE CATEGORIA = 2 AND EmpleadoUni.EMPLEADO_ID IS NULL)
		   BEGIN
			RAISERROR('EL EMPLEADO NO TIENE UN TÍTULO UNIVERSITARIO REGISTRADO POR LO QUE NO CUMPLE CON LOS REQUERIMIENTOS MÍNIMOS PARA SER NOMBRADO', 16, 1);
			ROLLBACK TRANSACTION;
		   END
	END


	select * from PUESTOS

	GO


/*
	TRIGGER QUE VERIFICA QUE SI EL GRADO CORRESPONDE A UN 
	GRADO MENOR A UNIVERSITARIO CAMBIE LA CATEGORIA A 1 
	O SI GRADO UNIVERSITARIO CAMBIE LA CATEGORIA A 2
*/

CREATE OR ALTER TRIGGER TR_VERIFICAR_GRADO_CATEGORIA_TITULO
ON GRADOS_ACADEMICOS AFTER INSERT
AS 
BEGIN
	
	DECLARE @CAT_INGRESADA INT;
	DECLARE @GRADO_INGRESADO VARCHAR(22);

	SELECT @CAT_INGRESADA  = CATEGORIA, @GRADO_INGRESADO = GRADO
	FROM inserted I;

	IF((@GRADO_INGRESADO = 'CERT' OR @GRADO_INGRESADO = 'CURS') AND @CAT_INGRESADA > 1)
		BEGIN
			UPDATE GA
			SET GA.CATEGORIA = 1
			FROM GRADOS_ACADEMICOS GA, inserted I
			WHERE GA.ID = I.ID

		END
	IF((@GRADO_INGRESADO = 'BACH' OR @GRADO_INGRESADO = 'DIPL' OR @GRADO_INGRESADO = 'LICI' OR @GRADO_INGRESADO = 'MAES' OR @GRADO_INGRESADO = 'DOCT'))
		BEGIN
			UPDATE GA
			SET GA.CATEGORIA = 2
			FROM GRADOS_ACADEMICOS GA, inserted I
			WHERE GA.ID = I.ID
		END

END
GO

CREATE OR ALTER TRIGGER TR_VERIFICAR_PUNTOS_TITULO
ON GRADOS_ACADEMICOS AFTER INSERT
AS 
BEGIN
	
	DECLARE @GRADO_INGRESADO VARCHAR(22);

	SELECT @GRADO_INGRESADO = GRADO
	FROM inserted I;
	
	IF(@GRADO_INGRESADO = 'CURS')
		BEGIN 
			UPDATE GA
			SET GA.PUNTOS = 0
			FROM GRADOS_ACADEMICOS GA, inserted I
			WHERE GA.ID = I.ID
		END
	IF(@GRADO_INGRESADO = 'CERT' OR @GRADO_INGRESADO = 'DIPL')
		BEGIN 
			UPDATE GA
			SET GA.PUNTOS = 1
			FROM GRADOS_ACADEMICOS GA, inserted I
			WHERE GA.ID = I.ID
		END
	IF(@GRADO_INGRESADO = 'BACH')
		BEGIN 
			UPDATE GA
			SET GA.PUNTOS = 2
			FROM GRADOS_ACADEMICOS GA, inserted I
			WHERE GA.ID = I.ID
		END

	IF(@GRADO_INGRESADO = 'LICI')
		BEGIN 
			UPDATE GA
			SET GA.PUNTOS = 3
			FROM GRADOS_ACADEMICOS GA, inserted I
			WHERE GA.ID = I.ID
		END

	IF(@GRADO_INGRESADO = 'MAES' OR @GRADO_INGRESADO = 'DOCT')
		BEGIN 
			UPDATE GA
			SET GA.PUNTOS = 4
			FROM GRADOS_ACADEMICOS GA, inserted I
			WHERE GA.ID = I.ID
		END
END
GO



